version: '3.7'

services:

    mysql_db:
        container_name: mysql_container
        image: mysql:8

        command: --default-authentication-plugin=mysql_native_password

        environment:
            LANG: C.UTF-8
            MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD:-root}
            MYSQL_USER: ${MYSQL_USER:-admin}
            MYSQL_PASSWORD: ${MYSQL_PASSWORD:-admin}
            MYSQL_DATABASE: ${MYSQL_DATABASE:-database}

        volumes:
            - ./initdb:/docker-entrypoint-initdb.d
            - ./mysql:/var/lib/mysql/

        ports:
            - ${MYSQL_PORT:-3306}:3306

        restart: unless-stopped

        healthcheck:
            test: [ 'CMD', 'mysqladmin', 'ping', '-proot' ]
            interval: 1m
            timeout: 5s
            retries: 5
            start_period: 3m

        deploy:
            resources:
                limits:
                    cpus: '1'
                    memory: 2G

# ============ !!!!! ============
# Start:
# docker-compose --compatibility up -d
# -------------------------------
# Access to MySQL:
# Root password: root
# URL: localhost:3306
# Database: database
# Username: admin
# Password: admin
# -------------------------------
# Stop lifted containers:
# docker-compose --compatibility stop
# -------------------------------
# Start stopped containers
# docker-compose --compatibility start
# -------------------------------
# Stop and delete containers and network:
# docker-compose --compatibility down
# -------------------------------
# Delete 'mysql' directory
# sudo rm -r mysql

